export const data = [
  {
    id: 1,
    song: "1.mp3",
    genre: "rock",
    track: "Enemy",
    group: "Imagine Dragons",
    year: 2019,
  },
  {
    id: 2,
    genre: "rock",
    track: "Enemy",
    group: "Imagine Dragons",
    year: 2019,
    song: "2.mp3",
  },
  {
    id: 3,
    genre: "rock",
    track: "Enemy",
    group: "Imagine Dragons",
    year: 2019,
    song: "3.mp3",
  },
  {
    id: 4,
    genre: "rock",
    track: "Enemy",
    group: "Imagine Dragons",
    year: 2019,
    song: "4.mp3",
  },
  {
    id: 5,
    genre: "rock",
    track: "Enemy",
    group: "Imagine Dragons",
    year: 2019,
    song: "5.mp3",
  },
  {
    id: 6,
    genre: "rock",
    track: "Enemy",
    group: "Imagine Dragons",
    year: 2019,
    song: "6.mp3",
  },
  {
    id: 7,
    genre: "rock",
    track: "Enemy",
    group: "Imagine Dragons",
    year: 2019,
    song: "7.mp3",
  },
];
